---
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.Integer"
  description: "The accounting port."
  shortDescription: "The accounting port."
  name: "cas.authn.mfa.radius.client.accounting-port"
  defaultValue: 1813
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.Integer"
  description: "The authentication port."
  shortDescription: "The authentication port."
  name: "cas.authn.mfa.radius.client.authentication-port"
  defaultValue: 1812
- required: true
  module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.String"
  description: "Server address to connect and establish a session."
  shortDescription: "Server address to connect and establish a session."
  name: "cas.authn.mfa.radius.client.inet-address"
  defaultValue: "localhost"
- required: true
  module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.String"
  description: "Secret/password to use for the initial bind."
  shortDescription: "Secret/password to use for the initial bind."
  name: "cas.authn.mfa.radius.client.shared-secret"
  defaultValue: "N0Sh@ar3d$ecReT"
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.Integer"
  description: "Socket connection timeout in milliseconds."
  shortDescription: "Socket connection timeout in milliseconds."
  name: "cas.authn.mfa.radius.client.socket-timeout"
  defaultValue: 0
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "The NAS identifier."
  shortDescription: "The NAS identifier."
  name: "cas.authn.mfa.radius.server.nas-identifier"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "The NAS IP address."
  shortDescription: "The NAS IP address."
  name: "cas.authn.mfa.radius.server.nas-ip-address"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "The NAS IPv6 address."
  shortDescription: "The NAS IPv6 address."
  name: "cas.authn.mfa.radius.server.nas-ipv6-address"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Long"
  description: "The NAS port."
  shortDescription: "The NAS port."
  name: "cas.authn.mfa.radius.server.nas-port"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Long"
  description: "The NAS port id."
  shortDescription: "The NAS port id."
  name: "cas.authn.mfa.radius.server.nas-port-id"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Integer"
  description: "The NAS port type."
  shortDescription: "The NAS port type."
  name: "cas.authn.mfa.radius.server.nas-port-type"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Long"
  description: "The NAS real port."
  shortDescription: "The NAS real port."
  name: "cas.authn.mfa.radius.server.nas-real-port"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "Radius protocol to use when communicating with the server."
  shortDescription: "Radius protocol to use when communicating with the server."
  name: "cas.authn.mfa.radius.server.protocol"
  defaultValue: "EAP_MSCHAPv2"
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Integer"
  description: "Number of re-try attempts when dealing with connection and authentication\
    \ failures."
  shortDescription: "Number of re-try attempts when dealing with connection and authentication\
    \ failures."
  name: "cas.authn.mfa.radius.server.retries"
  defaultValue: 3
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.Integer"
  description: "The accounting port."
  shortDescription: "The accounting port."
  name: "cas.authn.radius.client.accounting-port"
  defaultValue: 1813
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.Integer"
  description: "The authentication port."
  shortDescription: "The authentication port."
  name: "cas.authn.radius.client.authentication-port"
  defaultValue: 1812
- required: true
  module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.String"
  description: "Server address to connect and establish a session."
  shortDescription: "Server address to connect and establish a session."
  name: "cas.authn.radius.client.inet-address"
  defaultValue: "localhost"
- required: true
  module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.String"
  description: "Secret/password to use for the initial bind."
  shortDescription: "Secret/password to use for the initial bind."
  name: "cas.authn.radius.client.shared-secret"
  defaultValue: "N0Sh@ar3d$ecReT"
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusClientProperties"
  type: "java.lang.Integer"
  description: "Socket connection timeout in milliseconds."
  shortDescription: "Socket connection timeout in milliseconds."
  name: "cas.authn.radius.client.socket-timeout"
  defaultValue: 0
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusProperties"
  type: "java.lang.Boolean"
  description: "Whether authentication errors should be skipped and fail over to the\
    \ next server."
  shortDescription: "Whether authentication errors should be skipped and fail over\
    \ to the next server."
  name: "cas.authn.radius.failover-on-authentication-failure"
  defaultValue: false
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusProperties"
  type: "java.lang.Boolean"
  description: "Whether catastrophic errors should be skipped and fail over to the\
    \ next server."
  shortDescription: "Whether catastrophic errors should be skipped and fail over to\
    \ the next server."
  name: "cas.authn.radius.failover-on-exception"
  defaultValue: false
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.radius.name"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "The NAS identifier."
  shortDescription: "The NAS identifier."
  name: "cas.authn.radius.server.nas-identifier"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "The NAS IP address."
  shortDescription: "The NAS IP address."
  name: "cas.authn.radius.server.nas-ip-address"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "The NAS IPv6 address."
  shortDescription: "The NAS IPv6 address."
  name: "cas.authn.radius.server.nas-ipv6-address"
  defaultValue: ""
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Long"
  description: "The NAS port."
  shortDescription: "The NAS port."
  name: "cas.authn.radius.server.nas-port"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Long"
  description: "The NAS port id."
  shortDescription: "The NAS port id."
  name: "cas.authn.radius.server.nas-port-id"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Integer"
  description: "The NAS port type."
  shortDescription: "The NAS port type."
  name: "cas.authn.radius.server.nas-port-type"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Long"
  description: "The NAS real port."
  shortDescription: "The NAS real port."
  name: "cas.authn.radius.server.nas-real-port"
  defaultValue: -1
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.String"
  description: "Radius protocol to use when communicating with the server."
  shortDescription: "Radius protocol to use when communicating with the server."
  name: "cas.authn.radius.server.protocol"
  defaultValue: "EAP_MSCHAPv2"
- module: "cas-server-support-radius"
  owner: "org.apereo.cas.configuration.model.support.radius.RadiusServerProperties"
  type: "java.lang.Integer"
  description: "Number of re-try attempts when dealing with connection and authentication\
    \ failures."
  shortDescription: "Number of re-try attempts when dealing with connection and authentication\
    \ failures."
  name: "cas.authn.radius.server.retries"
  defaultValue: 3
