---
- required: true
  module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.util.List<java.lang.String>"
  description: "Node addresses."
  shortDescription: "Node addresses."
  name: "cas.audit.couchbase.addresses"
  defaultValue: ""
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.Boolean"
  description: "Whether audit records should be executed asynchronously."
  shortDescription: "Whether audit records should be executed asynchronously."
  name: "cas.audit.couchbase.asynchronous"
  defaultValue: false
- required: true
  module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "Bucket name."
  shortDescription: "Bucket name."
  name: "cas.audit.couchbase.bucket"
  defaultValue: "testbucket"
- required: true
  module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "Cluster password."
  shortDescription: "Cluster password."
  name: "cas.audit.couchbase.cluster-password"
  defaultValue: ""
- required: true
  module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "Cluster username."
  shortDescription: "Cluster username."
  name: "cas.audit.couchbase.cluster-username"
  defaultValue: ""
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of connection timeout."
  shortDescription: "String representation of connection timeout."
  name: "cas.audit.couchbase.connection-timeout"
  defaultValue: "PT60S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of idle connection timeout."
  shortDescription: "String representation of idle connection timeout."
  name: "cas.audit.couchbase.idle-connection-timeout"
  defaultValue: "PT60S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of KV timeout."
  shortDescription: "String representation of KV timeout."
  name: "cas.audit.couchbase.kv-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.Integer"
  description: "Maximum number of connections made to the cluster."
  shortDescription: "Maximum number of connections made to the cluster."
  name: "cas.audit.couchbase.max-http-connections"
  defaultValue: 5
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.Long"
  description: "Allows to customize the maximum number of requests allowed in the\
    \ retry timer."
  shortDescription: "Allows to customize the maximum number of requests allowed in\
    \ the retry timer."
  name: "cas.audit.couchbase.max-num-requests-in-retry"
  defaultValue: 32768
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.Integer"
  description: "Maximum number of parallel threads made for queries."
  shortDescription: "Maximum number of parallel threads made for queries."
  name: "cas.audit.couchbase.max-parallelism"
  defaultValue: 0
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of query threshold."
  shortDescription: "String representation of query threshold."
  name: "cas.audit.couchbase.query-threshold"
  defaultValue: "PT30S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of query timeout."
  shortDescription: "String representation of query timeout."
  name: "cas.audit.couchbase.query-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "Query scan consistency. By default, the query engine will return whatever\
    \ is currently in the index at the time of query (this mode is also called {@code\
    \ NOT_BOUNDED}). If you need to include everything that has just been written,\
    \ a different scan consistency must be chosen. If {@code REQUEST_PLUS} is chosen,\
    \ it will likely take a bit longer to return the results but the query engine\
    \ will make sure that it is as up-to-date as possible. Accepted values are: {@code\
    \ NOT_BOUNDED, REQUEST_PLUS}."
  shortDescription: "Query scan consistency."
  name: "cas.audit.couchbase.scan-consistency"
  defaultValue: "NOT_BOUNDED"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of scan timeout."
  shortDescription: "String representation of scan timeout."
  name: "cas.audit.couchbase.scan-wait-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of search timeout."
  shortDescription: "String representation of search timeout."
  name: "cas.audit.couchbase.search-timeout"
  defaultValue: "PT30S"
- module: "cas-server-support-audit-couchbase"
  owner: "org.apereo.cas.configuration.model.core.audit.AuditCouchbaseProperties"
  type: "java.lang.String"
  description: "String representation of view timeout."
  shortDescription: "String representation of view timeout."
  name: "cas.audit.couchbase.view-timeout"
  defaultValue: "PT30S"
